<?php

namespace Coyote\Vpn;

/**
 * Generates swanctl.conf configuration files for StrongSwan.
 *
 * Converts Coyote VPN configuration to StrongSwan's swanctl format.
 */
class SwanctlConfig
{
    /**
     * Generate swanctl.conf content from configuration.
     *
     * @param array $config VPN configuration
     * @return string Configuration file content
     */
    public function generate(array $config): string
    {
        $conf = "# Generated by Coyote Linux - do not edit manually\n\n";

        // Connections section
        $conf .= $this->generateConnections($config['tunnels'] ?? []);

        // Secrets section
        $conf .= $this->generateSecrets($config['tunnels'] ?? []);

        // Pools section (for virtual IPs if needed)
        if (!empty($config['pools'])) {
            $conf .= $this->generatePools($config['pools']);
        }

        return $conf;
    }

    /**
     * Generate the connections section.
     *
     * @param array $tunnels Tunnel configurations
     * @return string Connections configuration
     */
    private function generateConnections(array $tunnels): string
    {
        if (empty($tunnels)) {
            return "connections {\n}\n\n";
        }

        $conf = "connections {\n";

        foreach ($tunnels as $name => $tunnel) {
            if (!($tunnel['enabled'] ?? true)) {
                continue;
            }

            $conf .= $this->generateConnection($name, $tunnel);
        }

        $conf .= "}\n\n";

        return $conf;
    }

    /**
     * Generate a single connection configuration.
     *
     * @param string $name Connection name
     * @param array $tunnel Tunnel configuration
     * @return string Connection configuration
     */
    private function generateConnection(string $name, array $tunnel): string
    {
        $conf = "    {$name} {\n";

        // IKE version
        $version = $tunnel['version'] ?? 2;
        $conf .= "        version = {$version}\n";

        // Addresses
        $localAddr = $tunnel['local_address'] ?? '%any';
        $remoteAddr = $tunnel['remote_address'] ?? '%any';
        $conf .= "        local_addrs = {$localAddr}\n";
        $conf .= "        remote_addrs = {$remoteAddr}\n";

        // IKE proposals
        if (!empty($tunnel['proposals'])) {
            $proposals = implode(',', $tunnel['proposals']);
            $conf .= "        proposals = {$proposals}\n";
        }

        // Rekey time
        if (isset($tunnel['rekey_time'])) {
            $conf .= "        rekey_time = {$tunnel['rekey_time']}s\n";
        }

        // DPD settings
        if (isset($tunnel['dpd_delay'])) {
            $conf .= "        dpd_delay = {$tunnel['dpd_delay']}s\n";
        }

        // Local authentication
        $conf .= "        local {\n";
        $conf .= "            auth = " . ($tunnel['local_auth'] ?? 'psk') . "\n";
        if (isset($tunnel['local_id'])) {
            $conf .= "            id = {$tunnel['local_id']}\n";
        }
        $conf .= "        }\n";

        // Remote authentication
        $conf .= "        remote {\n";
        $conf .= "            auth = " . ($tunnel['remote_auth'] ?? 'psk') . "\n";
        if (isset($tunnel['remote_id'])) {
            $conf .= "            id = {$tunnel['remote_id']}\n";
        }
        $conf .= "        }\n";

        // Child SA (traffic selectors)
        $conf .= "        children {\n";
        $conf .= "            {$name} {\n";

        if (isset($tunnel['local_ts'])) {
            $conf .= "                local_ts = {$tunnel['local_ts']}\n";
        }
        if (isset($tunnel['remote_ts'])) {
            $conf .= "                remote_ts = {$tunnel['remote_ts']}\n";
        }

        // ESP proposals
        if (!empty($tunnel['esp_proposals'])) {
            $espProposals = implode(',', $tunnel['esp_proposals']);
            $conf .= "                esp_proposals = {$espProposals}\n";
        }

        // Actions
        $startAction = $tunnel['start_action'] ?? 'trap';
        $conf .= "                start_action = {$startAction}\n";

        if (isset($tunnel['dpd_action'])) {
            $conf .= "                dpd_action = {$tunnel['dpd_action']}\n";
        }
        if (isset($tunnel['close_action'])) {
            $conf .= "                close_action = {$tunnel['close_action']}\n";
        }

        // Lifetime
        if (isset($tunnel['life_time'])) {
            $conf .= "                life_time = {$tunnel['life_time']}s\n";
        }

        $conf .= "            }\n";
        $conf .= "        }\n";

        $conf .= "    }\n";

        return $conf;
    }

    /**
     * Generate the secrets section.
     *
     * @param array $tunnels Tunnel configurations
     * @return string Secrets configuration
     */
    private function generateSecrets(array $tunnels): string
    {
        $conf = "secrets {\n";

        foreach ($tunnels as $name => $tunnel) {
            if (!($tunnel['enabled'] ?? true)) {
                continue;
            }

            // PSK secret
            if (isset($tunnel['psk'])) {
                $conf .= "    ike-{$name} {\n";

                // ID for the secret
                $ids = [];
                if (isset($tunnel['local_id'])) {
                    $ids[] = $tunnel['local_id'];
                }
                if (isset($tunnel['remote_id'])) {
                    $ids[] = $tunnel['remote_id'];
                }
                if (isset($tunnel['remote_address']) && $tunnel['remote_address'] !== '%any') {
                    $ids[] = $tunnel['remote_address'];
                }

                if (!empty($ids)) {
                    $conf .= "        id = " . implode(',', $ids) . "\n";
                }

                // Quote the secret and escape any internal quotes
                $escapedPsk = str_replace('"', '\\"', $tunnel['psk']);
                $conf .= "        secret = \"{$escapedPsk}\"\n";

                $conf .= "    }\n";
            }

            // Certificate-based secrets would go here
            if (isset($tunnel['private_key'])) {
                $conf .= "    private-{$name} {\n";
                $conf .= "        file = {$tunnel['private_key']}\n";
                $conf .= "    }\n";
            }
        }

        $conf .= "}\n\n";

        return $conf;
    }

    /**
     * Generate the pools section for virtual IPs.
     *
     * @param array $pools Pool configurations
     * @return string Pools configuration
     */
    private function generatePools(array $pools): string
    {
        $conf = "pools {\n";

        foreach ($pools as $name => $pool) {
            $conf .= "    {$name} {\n";
            $conf .= "        addrs = {$pool['range']}\n";

            if (isset($pool['dns'])) {
                $dns = is_array($pool['dns']) ? implode(',', $pool['dns']) : $pool['dns'];
                $conf .= "        dns = {$dns}\n";
            }

            $conf .= "    }\n";
        }

        $conf .= "}\n\n";

        return $conf;
    }

    /**
     * Validate a configuration before generating.
     *
     * @param array $config Configuration to validate
     * @return array List of validation errors
     */
    public function validate(array $config): array
    {
        $errors = [];

        foreach ($config['tunnels'] ?? [] as $name => $tunnel) {
            // Validate tunnel name
            if (!preg_match('/^[a-zA-Z][a-zA-Z0-9_-]*$/', $name)) {
                $errors[] = "Invalid tunnel name: {$name}";
            }

            // Check for required fields when using PSK
            if (($tunnel['local_auth'] ?? 'psk') === 'psk') {
                if (empty($tunnel['psk'])) {
                    $errors[] = "Tunnel {$name}: PSK is required for PSK authentication";
                }
            }
        }

        return $errors;
    }
}
