<?php

namespace Coyote\System\Subsystem;

/**
 * NTP time synchronization subsystem.
 *
 * Handles:
 * - NTP server configuration
 * - busybox ntpd service management
 * - /etc/conf.d/ntpd configuration
 */
class NtpSubsystem extends AbstractSubsystem
{
    public function getName(): string
    {
        return 'ntp';
    }

    public function requiresCountdown(): bool
    {
        // Changing NTP servers cannot cause loss of remote access
        return false;
    }

    public function getConfigKeys(): array
    {
        return [
            'services.ntp',
            'system.timeserver',
        ];
    }

    public function hasChanges(array $working, array $running): bool
    {
        return $this->valuesChanged($working, $running, $this->getConfigKeys());
    }

    public function apply(array $config): array
    {
        $errors = [];
        $priv = $this->getPrivilegedExecutor();

        $ntpConfig = $this->getNestedValue($config, 'services.ntp', []);
        $enabled = $ntpConfig['enabled'] ?? true;
        $servers = $ntpConfig['servers'] ?? ['pool.ntp.org'];

        // Fallback to legacy system.timeserver if services.ntp.servers is empty
        if (empty($servers)) {
            $legacyServer = $this->getNestedValue($config, 'system.timeserver', '');
            if (!empty($legacyServer)) {
                $servers = [$legacyServer];
            }
        }

        if (!$enabled || empty($servers)) {
            // Stop NTP service if disabled or no servers configured
            $result = $priv->rcService('ntpd', 'stop');
            if (!$result['success']) {
                $errors[] = 'Failed to stop ntpd: ' . $result['output'];
            }

            if (!empty($errors)) {
                return $this->failure('NTP configuration had errors', $errors);
            }

            return $this->success('NTP service disabled');
        }

        // Build ntpd command-line options with -p flags for each server
        $ntpdOpts = '-N';
        foreach ($servers as $server) {
            $server = trim($server);
            if (!empty($server)) {
                $ntpdOpts .= ' -p ' . escapeshellarg($server);
            }
        }

        // Write /etc/conf.d/ntpd with NTPD_OPTS
        $confContent = "# NTP daemon configuration\n";
        $confContent .= "# Generated by Coyote Linux web admin\n\n";
        $confContent .= "NTPD_OPTS=\"{$ntpdOpts}\"\n";

        $result = $priv->writeFile('/etc/conf.d/ntpd', $confContent);
        if (!$result['success']) {
            $errors[] = 'Failed to write /etc/conf.d/ntpd: ' . $result['output'];
        }

        // Restart ntpd service to apply changes
        $result = $priv->rcService('ntpd', 'restart');
        if (!$result['success']) {
            $errors[] = 'Failed to restart ntpd: ' . $result['output'];
        }

        if (!empty($errors)) {
            return $this->failure('NTP configuration had errors', $errors);
        }

        $serverList = implode(', ', $servers);
        return $this->success("NTP configured with servers: {$serverList}");
    }
}
